DDCE-2733 - Migrate from reactive mongo to hmrc mongo
hmrc/verify-your-identity-for-an-estate-frontend pull request #59
Opened 2022-10-31 14:12 UTC by frikit

2022-11-02 17:00 UTC, ina-tu reviewed
The back buttons on the pages have disappeared - see screenshots below:
Left is local environment, Right is Staging environment
<img width="500" alt="Screenshot 2022-11-02 at 17 02 18" src="https://user-images.githubusercontent.com/74660663/199554310-07037cfd-7810-49a8-acbd-b11896acb3cd.png">

<img width="500" alt="Screenshot 2022-11-02 at 17 02 33" src="https://user-images.githubusercontent.com/74660663/199554315-910c449f-ae76-4fc2-ba8f-e61543206fd3.png">

2022-11-02 17:35 UTC, ina-tu requested changes
when the link in the error summary is clicked, the "#value yes" (hyperlink) appears in the url (http://localhost:8831/verify-your-identity-for-an-estate/managed-by-agent#value-yes). This doesn't happen in staging environment - see screenshot below:

Left is local, Right is staging

<img width="500" alt="Screenshot 2022-11-02 at 17 11 51" src="https://user-images.githubusercontent.com/74660663/199560676-9277ff18-ccae-4ff0-a0f0-25b9bb20d78b.png">

2022-11-03 08:09 UTC, frikit commented on app/repositories/DefaultSessionRepository.scala
> +    collection.find(Filters.eq("_id", id)) headOption()
I fixed as I think is a good change it but in scala it is a valid syntax does the same as your example

2022-11-03 08:10 UTC, frikit commented on project/AppDependencies.scala
> +    "org.scalatestplus.play"      %% "scalatestplus-play"       % "5.1.0",
done

2022-11-03 08:10 UTC, frikit commented
@ina-tu fixed comments and reverted play-frontend-hmrc to avoid ui bugs

2022-11-03 10:19 UTC, ina-tu approved these changes

2022-11-03 10:20 UTC, merged